- hosts: local
  connection: local
  gather_facts: False
  vars_prompt:
    - name: key
      prompt: "What is the key of tag?"
    - name: value
      prompt: "Waht is the value of tag?"
  vars_files:
    - vars/ec2.yaml
  vars:
    region: us-east-1

  tasks:
    - name: EC2 Facts
      ec2_instance_facts:
        region: "{{ region }}"
        filters:
          "{{ {'tag:' + key: value} }}"
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
      register: ec2

    - name: Terminate instances
      ec2:
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        instance_ids: "{{ item.instance_id }}"
        state: absent
        wait: true
        region: "{{ region }}"
      with_items: "{{ ec2.instances }}"